CREATE DATABASE eshop COLLATE utf8_general_ci;


USE eshop;


CREATE TABLE personne (
    PER_ID INT AUTO_INCREMENT NOT NULL,
    PER_NOM VARCHAR(50) NOT NULL,
    PER_PRENOM VARCHAR(50) NOT NULL,
    PER_MAIL VARCHAR(150) NOT NULL,
    PER_TELEPHONE VARCHAR(20) NOT NULL,
    PER_ADRESSE VARCHAR(150) NOT NULL,
    PER_PASSWORD VARCHAR(300),
    PER_DATE_NAISSANCE DATE,
    PER_SIRET VARCHAR(14),
    PER_TYPE ENUM('C', 'F') NOT NULL DEFAULT 'C',
    PRIMARY KEY (PER_ID)
) ENGINE = InnoDb;



CREATE TABLE categorie (
    CAT_ID INT NOT NULL AUTO_INCREMENT,
    CAT_LIBELLE VARCHAR(50) NOT NULL,
    CAT_PARENT_ID INT, 
    PRIMARY KEY (CAT_ID)
) ENGINE = InnoDb;



CREATE TABLE produit (
    PRO_ID INT NOT NULL AUTO_INCREMENT,
    PRO_LIBELLE VARCHAR(50) NOT NULL,
    PRO_PRIX DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PRO_STOCK INT NOT NULL DEFAULT 0,
    PRO_PHOTO VARCHAR(250),
    PRO_NOTE DECIMAL(4, 2),
    PRO_FOURNISSEUR_ID INT, 
    PRIMARY KEY (PRO_ID)
) ENGINE = InnoDb;



CREATE TABLE produit_categorie (
    PRCA_CATEGORIE_ID INT NOT NULL, 
    PRCA_PRODUIT_ID INT NOT NULL, 
    PRIMARY KEY (PRCA_CATEGORIE_ID, PRCA_PRODUIT_ID)
) ENGINE = InnoDb;



CREATE TABLE paiement (
    PAIE_ID INT NOT NULL AUTO_INCREMENT,
    PAIE_TYPE ENUM('VISA', 'MASTERCARD', 'CHEQUE', 'LIQUIDE', 'AUTRE') NOT NULL DEFAULT 'AUTRE',
    PRIMARY KEY (PAIE_ID)
) ENGINE = InnoDb;



CREATE TABLE commande (
    CMD_ID INT NOT NULL AUTO_INCREMENT,
    CMD_DATE DATETIME NOT NULL DEFAULT NOW(),
    CMD_CLIENT_ID INT NOT NULL, 
    CMD_PAIEMENT_ID INT NOT NULL, 
    CMD_PAIEMENT_AUTORISE BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (CMD_ID)
) ENGINE = InnoDb;



CREATE TABLE commande_detail (
    CDET_COMMANDE_ID INT NOT NULL, 
    CDET_PRODUIT_ID INT NOT NULL, 
    CDET_QUANTITE INT NOT NULL DEFAULT 1,
    PRIMARY KEY (CDET_COMMANDE_ID, CDET_PRODUIT_ID)
) ENGINE = InnoDb;



CREATE TABLE commentaire (
    COM_ID INT NOT NULL AUTO_INCREMENT,
    COM_CLIENT_ID INT NOT NULL, 
    COM_COMMANDE_ID INT NOT NULL, 
    COM_PRODUIT_ID INT NOT NULL, 
    COM_TEXTE TEXT NOT NULL,
    COM_ANONYMOUS BOOLEAN NOT NULL DEFAULT 1,
    COM_DATE DATETIME NOT NULL DEFAULT NOW(),
    PRIMARY KEY (COM_ID)
) ENGINE = InnoDb;




ALTER TABLE categorie
    ADD CONSTRAINT FK_CategorieParent
    FOREIGN KEY (CAT_PARENT_ID)
    REFERENCES categorie (CAT_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE;


ALTER TABLE produit
    ADD CONSTRAINT FK_ProduitFournisseur
    FOREIGN KEY (PRO_FOURNISSEUR_ID)
    REFERENCES personne (PER_ID)
    ON DELETE RESTRICT;


ALTER TABLE produit_categorie
    ADD CONSTRAINT FK_ProduitCategorieCategorie
    FOREIGN KEY (PRCA_CATEGORIE_ID)
    REFERENCES categorie (CAT_ID)
    ON DELETE CASCADE;

ALTER TABLE produit_categorie
    ADD CONSTRAINT FK_ProduitCategorieProduit
    FOREIGN KEY (PRCA_PRODUIT_ID)
    REFERENCES produit (PRO_ID)
    ON DELETE CASCADE;


ALTER TABLE commande
    ADD CONSTRAINT FK_CommandeClient
    FOREIGN KEY (CMD_CLIENT_ID)
    REFERENCES personne (PER_ID);


ALTER TABLE commande
    ADD CONSTRAINT FK_CommandePaiement
    FOREIGN KEY (CMD_PAIEMENT_ID)
    REFERENCES paiement (PAIE_ID);


ALTER TABLE commande_detail
    ADD CONSTRAINT FK_CommandeDetailCommande
    FOREIGN KEY (CDET_COMMANDE_ID)
    REFERENCES commande (CMD_ID)
    ON DELETE CASCADE;

ALTER TABLE commande_detail
    ADD CONSTRAINT FK_CommandeDetailProduit
    FOREIGN KEY (CDET_PRODUIT_ID)
    REFERENCES produit (PRO_ID);


ALTER TABLE commentaire
    ADD CONSTRAINT FK_CommentaireClient
    FOREIGN KEY (COM_CLIENT_ID)
    REFERENCES personne (PER_ID);


ALTER TABLE commentaire
    ADD CONSTRAINT FK_CommentaireCommande
    FOREIGN KEY (COM_COMMANDE_ID)
    REFERENCES commande (CMD_ID)
    ON DELETE CASCADE;


ALTER TABLE commentaire
    ADD CONSTRAINT FK_CommentaireProduit
    FOREIGN KEY (COM_PRODUIT_ID)
    REFERENCES produit (PRO_ID);



INSERT INTO personne (PER_NOM, PER_PRENOM, PER_MAIL, PER_TELEPHONE, PER_ADRESSE, PER_SIRET, PER_TYPE)
VALUES ('BABAR', 'Fournisseur', 'babar@fournisseur.fr', '0123457896', '23 rue des Environs, 35000 RENNES', '12345678910', 'F');


INSERT INTO personne (PER_NOM, PER_PRENOM, PER_MAIL, PER_TELEPHONE, PER_ADRESSE, PER_PASSWORD, PER_DATE_NAISSANCE, PER_TYPE)
VALUES ('PERROUAULT', 'Jérémy', 'jeremy@gmail.com', '0666254185', '25 rue des Environs, 35000 RENNES', '123456', '1997-11-02', 'C');



INSERT INTO categorie (CAT_LIBELLE)
VALUES
('Parachutes'),
('Combinaisons');



INSERT INTO produit (PRO_LIBELLE, PRO_PRIX, PRO_STOCK, PRO_FOURNISSEUR_ID)
VALUES
('Parachute de France', 7000.50, 2, 1),
('Combinaison coton', '500', 20, 1),
('Casque vidéo', '1000', 5, 1);


INSERT INTO produit_categorie (PRCA_CATEGORIE_ID, PRCA_PRODUIT_ID)
VALUES
(1, 1),
(2, 2),
(2, 3);


INSERT INTO paiement 
VALUES
(1, 'VISA'),
(10, 'MASTERCARD');



INSERT INTO commande (CMD_CLIENT_ID, CMD_PAIEMENT_ID, CMD_PAIEMENT_AUTORISE)
VALUES
(2, 1, 1),
(2, 10, 0);



INSERT INTO commande_detail (CDET_COMMANDE_ID, CDET_PRODUIT_ID, CDET_QUANTITE) VALUES
(1, 2, 1),
(1, 3, 5),
(2, 1, 1);


INSERT INTO commentaire (COM_CLIENT_ID, COM_COMMANDE_ID, COM_PRODUIT_ID, COM_TEXTE, COM_ANONYMOUS)
VALUES
(1, 1, 2, 'Ceci est un commentaire.', True);


